### ISSUE TITLE
Add ability to rename schedules

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#318] opened 2020-07-27 01:17 UTC
After #317 is done, we need to actually implement the design we come up with, this will involve changing the redux for schedules, adding additional components, and creating tests for it

**Comment by gannonprudhomme** [comment] 2020-08-10 23:21
Closing, duplicate of #296 . Re-open if this is wrong though

**Closed** 2020-08-10 23:22 UTC
Labels: feature, frontend
